default: &default
  adapter: postgresql
  encoding: unicode
  username: lsamon
  password: password
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: futsal_homebush_league_development

test:
  <<: *default
  database: futsal_homebush_league_test

production:
  <<: *default
  database: futsal_homebush_league_production
  username: futsal_homebush_league
  password: <%= ENV['FUTSAL_HOMEBUSH_LEAGUE_DATABASE_PASSWORD'] %>
